set(INCLUDE_PATH ${CMAKE_SOURCE_DIR}/include)

set(SOURCE_PATH ${CMAKE_SOURCE_DIR}/source)

set(LIBS_PATH ${CMAKE_SOURCE_DIR})

set(SFML_DIR "D:/SFML-2.6.1/lib/cmake/SFML")

set(QT_PATH "C:/Qt/Qt5.14.2/5.14.2")

set(EXECUTABLE_OUTPUT_PATH ${CMAKE_SOURCE_DIR}/bin/${CMAKE_BUILD_TYPE})